name: tracky
description: Tracky App
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  google_sign_in: ^6.1.6
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.2.1

flutter:
  uses-material-design: true
  fonts:
      - family: Poppins
        fonts:
          - asset: fonts/Poppins-Black.ttf
          - asset: fonts/Poppins-Bold.ttf
          - asset: fonts/Poppins-Italic.ttf
          - asset: fonts/Poppins-Medium.ttf
          - asset: fonts/Poppins-Regular.ttf
          - asset: fonts/Poppins-SemiBold.ttf
  assets:
    - assets/
    - assets/js/