// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxUNmIwdGBqGZr-OjB42cwEIHYOlVpVs0',
    appId: '1:52574860367:web:8cc8e162a0d9d71135e63a',
    messagingSenderId: '52574860367',
    projectId: 'tracky-6ddd0',
    authDomain: 'tracky-6ddd0.firebaseapp.com',
    storageBucket: 'tracky-6ddd0.appspot.com',
    measurementId: 'G-CEJJR45NY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD517BsMu-kArWCF5bQD3RfVIbHO2reahQ',
    appId: '1:52574860367:android:069ffe5ad86677a135e63a',
    messagingSenderId: '52574860367',
    projectId: 'tracky-6ddd0',
    storageBucket: 'tracky-6ddd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuYlJc9OCFzyIAj8uHIFic0efjOCfkjew',
    appId: '1:52574860367:ios:1f5367bbf8ad5ce035e63a',
    messagingSenderId: '52574860367',
    projectId: 'tracky-6ddd0',
    storageBucket: 'tracky-6ddd0.appspot.com',
    iosBundleId: 'com.example.tracky',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuYlJc9OCFzyIAj8uHIFic0efjOCfkjew',
    appId: '1:52574860367:ios:9264d192c8ddca7735e63a',
    messagingSenderId: '52574860367',
    projectId: 'tracky-6ddd0',
    storageBucket: 'tracky-6ddd0.appspot.com',
    iosBundleId: 'com.example.tracky.RunnerTests',
  );
}
